# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-13 12:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('highscore', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='levelscore',
            unique_together=set([('user', 'level')]),
        ),
    ]
