# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-15 15:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explorer', '0003_challenge_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Target',
        ),
        migrations.AddField(
            model_name='challenge',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='challenge',
            name='avm_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='category',
            field=models.TextField(blank=True, help_text='Astronomical object type', null=True),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='description',
            field=models.TextField(help_text='Research page info'),
        ),
    ]
