# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-10 15:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('explorer', '0004_auto_20170815_1500'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challenge',
            name='badge',
        ),
    ]
