# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-10 15:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explorer', '0005_remove_challenge_badge'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='badge_total',
            field=models.IntegerField(default=0),
        ),
    ]
