# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-13 11:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explorer', '0006_challenge_badge_total'),
    ]

    operations = [
        migrations.RenameField(
            model_name='challenge',
            old_name='badge_total',
            new_name='sticker_total',
        ),
        migrations.AddField(
            model_name='mission',
            name='sticker_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='action',
            field=models.TextField(help_text='What the user should look for on investigate?'),
        ),
    ]
