# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-27 13:48
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explorer', '0008_challenge_is_last'),
    ]

    operations = [
        migrations.CreateModel(
            name='Body',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('schema', models.IntegerField(choices=[(0, 'MPC_MINOR_PLANET'), (1, 'MPC_COMET'), (2, 'JPL_MAJOR_PLANET')])),
                ('epochofel', models.FloatField(help_text='MJD')),
                ('orbinc', models.FloatField(help_text='IN')),
                ('longascnode', models.FloatField(help_text='OM')),
                ('argofperih', models.FloatField(help_text='Tp')),
                ('eccentricity', models.FloatField(help_text='EC')),
                ('dailymotion', models.FloatField(blank=True, help_text='n', null=True)),
                ('meananom', models.FloatField(blank=True, help_text='MA', null=True)),
                ('meandist', models.FloatField(blank=True, help_text='A', null=True)),
                ('perihdist', models.FloatField(blank=True, null=True)),
                ('epochofperih', models.FloatField(blank=True, null=True)),
                ('filter_list', models.CharField(help_text='JSON blob of filters', max_length=20)),
                ('exposuretime', models.FloatField()),
                ('active', models.BooleanField(default=True)),
                ('last_update', models.DateTimeField(default=datetime.datetime.utcnow)),
            ],
        ),
        migrations.AlterField(
            model_name='challenge',
            name='category',
            field=models.TextField(blank=True, help_text='What type of object is this?', null=True),
        ),
    ]
