# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-29 12:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explorer', '0009_auto_20171127_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='body',
            name='avm_code',
            field=models.CharField(default='1.1', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='challenge',
            name='avm_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
