# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-29 15:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explorer', '0010_auto_20171129_1232'),
    ]

    operations = [
        migrations.AddField(
            model_name='body',
            name='icon',
            field=models.CharField(choices=[('1.1.1-mars.png', 'Mars'), ('1.1.2-jupiter.png', 'Jupiter'), ('1.1.2-neptune.png', 'Neptune'), ('1.1.2-saturn.png', 'Saturn'), ('1.1.2-uranus.png', 'Uranus'), ('2.2-comet.png', 'Comet'), ('2.3-asteroid.png', 'Asteroid')], default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='body',
            name='epochofperih',
            field=models.FloatField(blank=True, help_text='Used for comets', null=True),
        ),
        migrations.AlterField(
            model_name='body',
            name='perihdist',
            field=models.FloatField(blank=True, help_text='Used for comets', null=True),
        ),
    ]
