# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-29 17:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explorer', '0011_auto_20171129_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='body',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
