# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-05 15:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explorer', '0012_body_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='body',
            options={'verbose_name_plural': 'bodies'},
        ),
        migrations.AlterField(
            model_name='body',
            name='argofperih',
            field=models.FloatField(help_text='W'),
        ),
    ]
