# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-06-07 09:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explorer', '0016_auto_20171207_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='patch',
            field=models.CharField(choices=[('patches/GetToKnowTheNightSky_patch.png', 'Mission 1'), ('patches/LifeAndDeathOfStars_patch.png', 'Mission 2'), ('patches/universeatlarge_patch.png', 'Mission 3')], max_length=40),
        ),
    ]
