# Generated by Django 2.1.7 on 2019-07-29 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('explorer', '0022_auto_20180802_1053'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='challenge',
            options={'ordering': ['mission', 'number']},
        ),
        migrations.AlterUniqueTogether(
            name='challenge',
            unique_together={('number', 'mission', 'active')},
        ),
    ]
