# Generated by Django 2.1.7 on 2022-02-02 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explorer', '0027_auto_20220202_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='icon',
            field=models.CharField(blank=True, choices=[('M1C2-comet-icon.png', 'Comet'), ('M1C1-planet-icon1.png', 'Planet'), ('M1-moon-icon.png', 'Moon'), ('M1C3Galaxy-icon-01.png', ' Galaxy M1'), ('M1C4-cluster-icon.png', 'Cluster M1'), ('M1C5-nebulae-icon.png', 'Nebula M1'), ('M1C7-asteroid-icon.png', 'Asteroid'), ('M2C1-OpenCluster-icon.png', 'Open Cluster'), ('M2C2-GlobularCluster-icon.png', 'Globular Cluster'), ('M2C3-SupernovaRemnant-icon.png', 'Supernova'), ('M2C4-PlanetaryNebula-icon.png', 'Planetary Nebula'), ('M2C5-StarFormingNebula-icon1.png', 'Nebula'), ('M3C1Spiral-icon.png', 'Spiral Galaxy'), ('M3C2-Elliptical-icon.png', 'Elliptical Galaxy'), ('M3C3-Irregular-icon.png', 'Irregular Galaxy'), ('M3C4-Groups-icon1.png', 'Galaxy Group')], max_length=40, null=True),
        ),
    ]
