# Generated by Django 3.2.19 on 2023-10-10 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explorer', '0030_auto_20220208_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='body',
            name='filter_list',
            field=models.CharField(help_text='JSON blob of filters', max_length=100),
        ),
    ]
