version: '2'
services:
  serol:
    mem_limit: 256m
    image: docker.lco.global/serol:latest
    environment:
      DB_HOST: MYSQL_HOST
      DB_NAME: serol
      DB_PASSWD: PASSWORD
      DB_USER: USERNAME
      EMAIL_USERNAME: EMAIL
      EMAIL_PASSWORD: EMAIL_PASSWORD
      SECRET_KEY: SECRET_KEY

    volumes:
    - /mnt/docker/serol/media:/var/www/html/media
    labels:
      io.rancher.container.pull_image: always
    command: gunicorn -w 4 -k gevent -b 0.0.0.0:80 serol.wsgi

  celerybeat:
    image: docker.lco.global/serol:celery
    environment:
      DB_HOST: MYSQL_HOST
      DB_NAME: serol
      DB_PASSWD: PASSWORD
      DB_USER: USERNAME
      EMAIL_USERNAME: EMAIL
      EMAIL_PASSWORD: EMAIL_PASSWORD
      SECRET_KEY: SECRET_KEY

    links:
    - redis:redis
    command:
    - celery
    - -A
    - serol
    - beat
    - -l
    - info

  celery:
    image: docker.lco.global/serol:celery
    environment:
      DB_HOST: MYSQL_HOST
      DB_NAME: serol
      DB_PASSWD: PASSWORD
      DB_USER: USERNAME
      EMAIL_USERNAME: EMAIL
      EMAIL_PASSWORD: EMAIL_PASSWORD
      SECRET_KEY: SECRET_KEY

    links:
    - redis:redis
    command:
    - celery
    - -A
    - serol
    - worker
    - -l
    - info

  redis:
    image: redis:3.2
