# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-21 12:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stickers', '0003_auto_20171113_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sticker',
            name='progress',
            field=models.CharField(choices=[('New', 'New'), ('Submitted', 'Submitted'), ('Observed', 'Observed'), ('Identify', 'Identify'), ('Analyse', 'Analyse'), ('Investigate', 'Investigate'), ('Summary', 'Summary'), ('Failed', 'Failed'), ('Retry', 'Retry')], max_length=20),
        ),
    ]
