# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-14 11:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stickers', '0004_auto_20171121_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sticker',
            name='progress',
            field=models.CharField(choices=[('New', 'New'), ('Submitted', 'Submitted'), ('Observed', 'Observed'), ('Identify', 'Identify'), ('Analyse', 'Analyse'), ('Investigate', 'Investigate'), ('Summary', 'Summary'), ('Failed', 'Failed')], max_length=20),
        ),
    ]
