# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-06-07 09:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stickers', '0005_auto_20180214_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sticker',
            name='filename',
            field=models.CharField(choices=[('stickers/M1C1Planets.png', 'Planets'), ('stickers/M1C2Comet.png', 'Comet'), ('stickers/M1C5Nebulae.png', 'M1 Nebulae'), ('stickers/M2C3SupernovaRemnant.png', 'M2 Supernova'), ('stickers/M3C1Spiral.png', 'M3 Spiral'), ('stickers/M3C4Groups.png', 'M3 Galaxy Group'), ('stickers/M1C1Planets.png', 'Planets v2'), ('stickers/M1C3Galaxy.png', 'M1 Galaxy'), ('stickers/M1C4Cluster.png', ' Star Cluster'), ('stickers/M2C1OpenCluster.png', 'Open Cluster'), ('stickers/M2C4PlanetaryNebula.png', 'Planetary Nebula'), ('stickers/M3C2Elliptical.png', 'Elliptical Galaxy'), ('stickers/M2C2GlobularCluster.png', 'Globular Cluster'), ('stickers/M2C5StarFormingNebula.png', 'Star forming nebula'), ('stickers/M3C3Irregular.png', 'Irregular Galaxy')], max_length=40),
        ),
    ]
