#!/bin/bash

TOPDIR="/var/www/serol"

# Generate cron wrapper to set correct environment variables
cat > $TOPDIR/cronwrapper << EOF
export PYTHONPATH="${PYTHONPATH}"
export DJANGO_SETTINGS_MODULE="${DJANGO_SETTINGS_MODULE}"
export SEROL_DB_NAME="${SEROL_DB_NAME}"
export SEROL_DB_HOST="${SEROL_DB_HOST}"
export SEROL_DB_USER="${SEROL_DB_USER}"
export SEROL_DB_PASSWD="${SEROL_DB_PASSWD}"
export SEROL_EMAIL_USERNAME="${SEROL_EMAIL_USERNAME}"
export SEROL_EMAIL_PASSWORD="${SEROL_EMAIL_PASSWORD}"
EOF

# Make cron wrapper executable
chmod +x $TOPDIR/cronwrapper

# Django static files
python $TOPDIR/manage.py collectstatic --noinput

python $TOPDIR/manage.py migrate

# Perform migrations and pull in fixtures
python $TOPDIR/manage.py migrate --noinput
#python $TOPDIR/manage.py loaddata full_catalogue.json

# Django static files
python $TOPDIR/manage.py collectstatic --noinput

# Run under supervisord
exec /usr/bin/supervisord -n -c /etc/supervisord.conf
