# Generated by Django 2.1.7 on 2019-04-15 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0003_auto_20180822_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progress',
            name='image_file',
            field=models.FileField(blank=True, null=True, upload_to='images'),
        ),
    ]
