# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-05 15:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0010_auto_20171121_1237'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
