# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-14 11:12
from __future__ import unicode_literals

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0014_auto_20180125_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progress',
            name='status',
            field=django_fsm.FSMField(choices=[('New', 'New'), ('Submitted', 'Submitted'), ('Observed', 'Observed'), ('Identify', 'Identify'), ('Analyse', 'Analyse'), ('Investigate', 'Investigate'), ('Summary', 'Summary'), ('Failed', 'Failed')], default='New', max_length=50),
        ),
    ]
