# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-16 15:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0015_auto_20180214_1112'),
    ]

    operations = [
        migrations.RenameField(
            model_name='progress',
            old_name='requestids',
            new_name='tracking_num',
        ),
    ]
