# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-02 13:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explorer', '0002_challenge_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='category',
            field=models.TextField(blank=True, null=True),
        ),
    ]
