# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-23 10:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explorer', '0007_auto_20171113_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='is_last',
            field=models.BooleanField(default=False),
        ),
    ]
