# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-07 14:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explorer', '0013_auto_20171205_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='action',
            field=models.TextField(help_text='What the user should do on Observe page'),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='category',
            field=models.CharField(blank=True, help_text='What type of object is this?', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='description',
            field=models.TextField(help_text='Start page info'),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='number',
            field=models.IntegerField(help_text='Which number in the mission is this challenge?'),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='sticker_total',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
