# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-07 14:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explorer', '0015_auto_20171207_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='action',
            field=models.CharField(help_text='What the user should do on Observe page', max_length=200),
        ),
    ]
