# Generated by Django 2.0.7 on 2018-08-02 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('explorer', '0017_auto_20180607_0950'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagline', models.CharField(max_length=200)),
                ('desc', models.TextField(blank=True, null=True)),
                ('link', models.CharField(blank=True, max_length=200, null=True)),
                ('img', models.CharField(blank=True, max_length=100, null=True)),
                ('site', models.CharField(blank=True, max_length=3, null=True)),
                ('published', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='FactCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('desc', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='FactTopic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='explorer.Fact')),
                ('factcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='explorer.FactCategory')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='facttopic',
            unique_together={('fact', 'factcategory')},
        ),
    ]
