# Generated by Django 2.0.7 on 2018-08-02 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('explorer', '0018_auto_20180802_1032'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='facttopic',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='facttopic',
            name='fact',
        ),
        migrations.RemoveField(
            model_name='facttopic',
            name='factcategory',
        ),
        migrations.AddField(
            model_name='fact',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='explorer.FactCategory'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='FactTopic',
        ),
    ]
