# Generated by Django 2.0.7 on 2018-08-02 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('explorer', '0020_auto_20180802_1052'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FactCategory',
        ),
    ]
