# Generated by Django 2.1.7 on 2019-09-25 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explorer', '0024_season'),
    ]

    operations = [
        migrations.AlterField(
            model_name='season',
            name='jsfile',
            field=models.CharField(choices=[('halloween.json', 'halloween'), ('asteroid-day.json', 'asteroid day'), ('equinox.json', 'equinox'), ('new-year.json', 'new year'), ('earth-day.json', 'earth day'), ('perseids.json', 'perseids'), ('christmas.json', 'christmas')], max_length=20),
        ),
    ]
