# Generated by Django 3.2.12 on 2022-02-08 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explorer', '0029_activity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'verbose_name_plural': 'activities'},
        ),
        migrations.AlterField(
            model_name='body',
            name='icon',
            field=models.CharField(choices=[('1.1.1-mars.png', 'Mars'), ('1.1.2-jupiter.png', 'Jupiter'), ('1.1.2-neptune.png', 'Neptune'), ('1.1.2-saturn.png', 'Saturn'), ('1.1.2-uranus.png', 'Uranus'), ('2.2-comet-icon.png', 'Comet'), ('2.3-asteroids-icon.png', 'Asteroid')], max_length=25),
        ),
    ]
