# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-27 10:20
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('explorer', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requestids', models.TextField()),
                ('status', models.SmallIntegerField(choices=[(0, 'Pending'), (1, 'Completed'), (2, 'Failed')], default=0)),
                ('last_update', models.DateTimeField(default=datetime.datetime.utcnow)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='explorer.Challenge')),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='explorer.Mission')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
