# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-02 13:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='progress',
            name='mission',
        ),
        migrations.AlterField(
            model_name='progress',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'Pending'), (1, 'Completed'), (2, 'Failed'), (3, 'Retry'), (4, 'Finished')], default=0),
        ),
    ]
