# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-18 12:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0002_user_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='archive_token',
            field=models.CharField(blank=True, help_text='Authentication for LCO archive', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='token',
            field=models.CharField(blank=True, help_text='Authentication for Valhalla', max_length=50, null=True),
        ),
    ]
