# Generated by Django 2.0.7 on 2018-08-22 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('explorer', '0022_auto_20180802_1053'),
        ('status', '0002_auto_20180807_0906'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='progress',
            unique_together={('user', 'challenge')},
        ),
    ]
