# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-11 11:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('explorer', '0003_challenge_category'),
        ('status', '0003_auto_20170811_1110'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='progress',
            unique_together=set([('user', 'challenge')]),
        ),
    ]
