# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-29 15:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0003_auto_20170818_1206'),
    ]

    operations = [
        migrations.AddField(
            model_name='progress',
            name='userrequestids',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
