# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-29 15:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0004_progress_userrequestids'),
    ]

    operations = [
        migrations.RenameField(
            model_name='progress',
            old_name='userrequestids',
            new_name='userrequestid',
        ),
    ]
