# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-15 15:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0004_auto_20170811_1144'),
    ]

    operations = [
        migrations.AddField(
            model_name='progress',
            name='target',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='progress',
            name='requestids',
            field=models.CharField(max_length=20),
        ),
    ]
