# Generated by Django 3.2.12 on 2022-02-14 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0006_alter_user_first_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='progress',
            name='requestgroup',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
