# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-01 15:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0006_analysis_analysisanswer_useranswer'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AnalysisAnswer',
            new_name='Answer',
        ),
        migrations.RenameModel(
            old_name='Analysis',
            new_name='Question',
        ),
        migrations.AlterModelOptions(
            name='progress',
            options={'verbose_name_plural': 'User Progress'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name_plural': 'questions'},
        ),
        migrations.RenameField(
            model_name='question',
            old_name='question',
            new_name='text',
        ),
        migrations.AlterUniqueTogether(
            name='progress',
            unique_together=set([]),
        ),
    ]
