# Generated by Django 3.2.12 on 2022-03-30 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0008_alter_progress_requestid'),
    ]

    operations = [
        migrations.AddField(
            model_name='progress',
            name='badge_shown',
            field=models.BooleanField(default=False),
        ),
    ]
