# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-13 15:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0008_auto_20170901_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='progress',
            name='frameids',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='progress',
            name='requestids',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='progress',
            name='userrequestid',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
