# Generated by Django 3.2.12 on 2022-06-29 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0009_progress_badge_shown'),
    ]

    operations = [
        migrations.AddField(
            model_name='progress',
            name='dec',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='progress',
            name='obsdate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='progress',
            name='ra',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
