# Generated by Django 3.2.19 on 2023-07-12 12:50

from django.db import migrations, models
import uuid


def update_user_uuid(apps, schema_editor):
    User = apps.get_model('status', 'User')
    for user in User.objects.all():
        user.uuid = uuid.uuid4()
        user.save()


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0011_progress_siteid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.AddField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, serialize=False),
        ),
        migrations.RunPython(update_user_uuid),
    ]
