# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-05 16:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0011_proposal'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='default_proposal',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='status.Proposal'),
            preserve_default=False,
        ),
    ]
