# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-25 13:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0012_user_default_proposal'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='progress',
            options={'verbose_name_plural': 'Challenge Progress'},
        ),
        migrations.AddField(
            model_name='user',
            name='advanced',
            field=models.BooleanField(default=False, help_text='Has user competed Mission 1?'),
        ),
    ]
