# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-25 14:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0013_auto_20180125_1304'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='advanced',
            new_name='mission_1',
        ),
        migrations.AddField(
            model_name='user',
            name='mission_2',
            field=models.BooleanField(default=False, help_text='Has user competed Mission 2?'),
        ),
        migrations.AddField(
            model_name='user',
            name='mission_3',
            field=models.BooleanField(default=False, help_text='Has user competed Mission 3?'),
        ),
    ]
