# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-10 15:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('explorer', '0006_challenge_badge_total'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonSticker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Sticker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(max_length=200)),
                ('filename', models.ImageField(upload_to='stickers')),
                ('progress', models.CharField(choices=[('New', 'New'), ('Submitted', 'Submitted'), ('Observed', 'Observed'), ('Failed', 'Failed'), ('Retry', 'Retry'), ('Completed', 'Completed'), ('Identify', 'Identify'), ('Analyse', 'Analyse'), ('Identify', 'Identify'), ('Investigate', 'Investigate')], max_length=20)),
                ('challenge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='explorer.Challenge')),
            ],
        ),
        migrations.AddField(
            model_name='personsticker',
            name='sticker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stickers.Sticker'),
        ),
        migrations.AddField(
            model_name='personsticker',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
