# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-13 11:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stickers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sticker',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
