# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-13 15:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stickers', '0002_sticker_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sticker',
            name='filename',
            field=models.ImageField(upload_to='stickers/'),
        ),
    ]
