# Generated by Django 2.1.7 on 2022-02-02 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stickers', '0006_auto_20180607_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sticker',
            name='filename',
            field=models.CharField(choices=[('stickers/M1C1Planets.png', 'Planets'), ('stickers/M1C2Comet.png', 'Comet'), ('stickers/M1C5Nebulae.png', 'M1 Nebulae'), ('stickers/M2C3SupernovaRemnant.png', 'M2 Supernova'), ('stickers/M2C3SupernovaRemnant2.png', 'M2 Supernova v2'), ('stickers/M3C1Spiral.png', 'M3 Spiral'), ('stickers/M3C1Spiral2.png', 'M3 Spiral v2'), ('stickers/M3C4Groups.png', 'M3 Galaxy Group'), ('stickers/M3C4Groups2.png', 'M3 Galaxy Group v2'), ('stickers/M1C1Planets.png', 'Planets v2'), ('stickers/M1C3Galaxy.png', 'M1 Galaxy'), ('stickers/M1C3Galaxy2.png', 'M1 Galaxy v2'), ('stickers/M1C4Cluster.png', ' Star Cluster'), ('stickers/M2C1OpenCluster.png', 'Open Cluster'), ('stickers/M2C4PlanetaryNebula.png', 'Planetary Nebula'), ('stickers/M3C2Elliptical.png', 'Elliptical Galaxy'), ('stickers/M2C2GlobularCluster.png', 'Globular Cluster'), ('stickers/M2C5StarFormingNebula.png', 'Star forming nebula'), ('stickers/M3C3Irregular.png', 'Irregular Galaxy')], max_length=40),
        ),
    ]
